sonar.projectKey=acaballero11_ecologistics
sonar.organization=acaballero11
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=false
