sonar.projectKey=ACaballero_ecologistics
sonar.organization=acaballero-org
sonar.sources=.
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Umbrales obligatorios (Quality Gate)
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300